config/routes.rb
Rails.application.routes.draw do
  get 'policies/privacy-policy'
  get 'policies/refund-policy'
  get 'policies/shipping-policy'
  get 'policies/terms-of-service'
  resources :products, only: %i[show], param: :handle
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  # Defines the root path route ("/")
  root "home#index"
  get "about" => "home#about"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product.rb
Product = Struct.new("Product", :handle, :title, :price, :branded, :colors, :sizes, :sale, :featuring_product, :limited_stock_message, keyword_init: true) do
  self::DATA = YAML.load_file(Rails.root.join("config", "products.yml")).freeze
  self::IMAGE_EXTNAMES = %w[.jpg .webp .png].to_set.freeze

  def self.all
    @all ||= Product::DATA.map { |handle, product| new(handle:, **product) }
  end

  def self.find(handle)
    new(handle:, **Product::DATA.fetch(handle))
  end

  def to_param
    handle
  end

  def to_partial_path
    "products/product"
  end

  def image_srcs
    Dir.foreach(Rails.root.join("public", "img", "products", handle, "main")).filter_map do |filename|
      "/img/products/#{handle}/main/#{filename}" if File.extname(filename).in?(Product::IMAGE_EXTNAMES)
    end
  end

  def first_image_src
    image_srcs.first
  end

  def outdated_price(currency = "GBP")
    ((price[currency] * 2).to_f / 100).ceil - 0.01
  end
end

app/models/site.rb
module Site
  YAML.load_file(Rails.root.join("config", "site.yml")).each do |k, v|
    define_singleton_method(k) { v }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @products = Product.all
    @featuring_products = @products.filter(&:featuring_product)
  end

  def about
  end
end

app/controllers/policies_controller.rb
class PoliciesController < ApplicationController
  # GET /policies/privacy-policy.html
  def privacy_policy
  end

  # GET /policies/refund-policy.html
  def refund_policy
  end

  # GET /policies/shipping-policy.html
  def shipping_policy
  end

  # GET /policies/terms-of-service.html
  def terms_of_service
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products/:handle.html
  def show
    @product = Product.find(params[:handle])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/home/_ab_roller.html.erb
<h2 class="text-xl mt-4">EFFECTIVE WAY TO PUMP UP ABS 💪 AND GAIN A FLAT STOMACH 🏆 AT HOME OR IN THE GYM 🏃‍♀️🥰</h2>
<p class="mt-4">HelsiFit™ Ab Roller adopts automatic rebound technology, which helps protect muscles from stress during exercise. Moreover, the auto-rebound feature helps beginners tighten their core, standardize movement, and keep exercising for longer periods of time. The built-in smart braking system makes the rebound smoother and protects the user from injury.</p>

<p class="font-bold mt-4">Auto Rebound Abdominal Wheel Design</p>

<p class="text-orange-400 mt-4">NEW UPGRADE FOR A BETTER EXPERIENCE</p>

<img src="/img/products/ab-roller/description/1.webp" class="rounded-lg mt-4" alt="Ab Roller">

<p class="text-orange-400 mt-4">Ease Reset</p>

<p class="font-bold mt-4">No Damage To Waist and Knees 🤸‍♀️</p>

<p class="text-orange-400 mt-4">WHEN THE ABDOMINAL WHEEL IS PUSHED TO THE TIGHTEST STATE, THERE WILL BE A REBOUND</p>

<img src="/img/products/ab-roller/description/2.webp" class="rounded-lg mt-4" alt="Ab Roller">

<p class="font-bold mt-4">Multifunctions 🧰</p>
<p class="mt-4">Besides traditional exercise, you can also practice plank support to fully exercise your core muscles, including arm, chest, abdomen, back, buttocks, and lower body muscles, etc.</p>

<p class="text-orange-400 mt-4">Precise Force</p>
<p class="font-bold mt-4">Work Up Good Abs 🧘‍♂️</p>

<img src="/img/products/ab-roller/description/3.webp" class="rounded-lg mt-4" alt="Ab Roller">

<p class="font-bold mt-4">Double Wheel Design🩱</p>
<p class="mt-4">The elbow support abdominal wheel is different from other single or thin-wheeled Ab wheels available in the market. It has wider front and rear wheels of 105mm for smooth rolling and better control. This Ab wheel can help you exercise every muscle and core while ensuring safer body control, especially if you are a beginner.</p>

<p class="text-orange-400 mt-4">Widened Wheels</p>
<p class="font-bold mt-4">Safe Stable and Anti-skid🛡️</p>

<img src="/img/products/ab-roller/description/4.webp" class="rounded-lg mt-4" alt="Ab Roller">

<p class="font-bold mt-4">Wear-resistant material🌿</p>
<p class="mt-4">The material around the product is soft and helps to insulate sound. It is safe to use and will not damage the floor. The thick foam padding provides protection for your elbows during extended periods of exercise. The non-slip sponge grip is sweat-absorbent, comfortable, and durable. It won't make any noise or scratch the floor, and it has a longer service life. Overall, this product is convenient to use and provides a comfortable and safe workout experience.</p>

<p class="font-bold mt-4">Convenient Design📱</p>
<p class="mt-4">Equipped with a mobile phone holder, stable and not falling off. Fully combine sports with entertainment to make sports more exciting.</p>

<img src="/img/products/ab-roller/description/5.jpeg" class="rounded-lg mt-4" alt="Ab Roller">

<p class="font-bold mt-4">Included in the package:<p>
<div class="pl-2">
  <ul style="list-style:disc">
    <li>Abdominal Wheel</li>
    <li>Kneeling Mat</li>
    <li>Counter</li>
  </ul>
</div>

app/views/home/_about_us.html.erb
<hr class="mx-auto w-1/2 bg-black dark:bg-white" />

<section id="about" class="widescreen:section-min-height tallscreen:section-min-height my-12 flex scroll-mt-16 flex-col-reverse items-center justify-center gap-8 p-6 sm:flex-row">
  <article class="sm:w-1/2">
    <h2 class="max-w-md text-center text-4xl font-bold text-slate-900 sm:text-left sm:text-5xl dark:text-white">
      <span class="text-indigo-700 dark:text-indigo-300">About Us</span>
    </h2>
    <p class="mt-4 max-w-md text-center text-2xl text-slate-700 sm:text-left dark:text-slate-400">At HelsiFit Fitness Store, we're dedicated to simplifying your path to a healthier, more active lifestyle. We believe in quality over quantity, offering meticulously selected exercise equipment to help you achieve your fitness goals efficiently at home.</p>
    <p class="mt-4 max-w-md text-center text-2xl text-slate-700 sm:text-left dark:text-slate-400">
      <a href="about.html" class="inline-block rounded bg-lime-500 px-4 py-2 font-bold text-white hover:bg-lime-600 active:bg-lime-400">Read more</a>
    </p>
  </article>
  <img class="w-1/2 rounded-2xl" src="/img/theme/about.webp" alt="About HelsiFit" />
</section>

app/views/home/_carousel.html.erb
<div id="default-carousel" class="relative w-full" data-carousel="slide">
  <!-- Carousel wrapper -->
  <div class="relative h-56 overflow-hidden rounded-lg md:h-96">
    <% Dir.foreach(Rails.root.join("public", "img", "products", "ab-roller", "main")) do |filename| %>
      <% next unless File.extname(filename).in?(%w[.jpg .webp .png]) %>
      <div class="hidden duration-700 ease-in-out" data-carousel-item>
        <img src="/img/products/ab-roller/main/<%= filename %>" class="absolute block w-full -translate-x-1/2 -translate-y-1/2 top-1/2 left-1/2" alt="Ab Roller">
      </div>
    <% end %>
  </div>
  <!-- Slider indicators -->
  <div class="absolute z-30 flex -translate-x-1/2 bottom-5 left-1/2 space-x-3 rtl:space-x-reverse">
    <button type="button" class="w-3 h-3 rounded-full" aria-current="true" aria-label="Slide 1" data-carousel-slide-to="0"></button>
    <button type="button" class="w-3 h-3 rounded-full" aria-current="false" aria-label="Slide 2" data-carousel-slide-to="1"></button>
    <button type="button" class="w-3 h-3 rounded-full" aria-current="false" aria-label="Slide 3" data-carousel-slide-to="2"></button>
  </div>
  <!-- Slider controls -->
  <button type="button" class="absolute top-0 start-0 z-30 flex items-center justify-center h-full px-4 cursor-pointer group focus:outline-none" data-carousel-prev>
    <span class="inline-flex items-center justify-center w-10 h-10 rounded-full bg-white/30 dark:bg-gray-800/30 group-hover:bg-white/50 dark:group-hover:bg-gray-800/60 group-focus:ring-4 group-focus:ring-white dark:group-focus:ring-gray-800/70 group-focus:outline-none">
      <svg class="w-4 h-4 text-white dark:text-gray-800 rtl:rotate-180" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 1 1 5l4 4"/>
      </svg>
      <span class="sr-only">Previous</span>
    </span>
  </button>
  <button type="button" class="absolute top-0 end-0 z-30 flex items-center justify-center h-full px-4 cursor-pointer group focus:outline-none" data-carousel-next>
    <span class="inline-flex items-center justify-center w-10 h-10 rounded-full bg-white/30 dark:bg-gray-800/30 group-hover:bg-white/50 dark:group-hover:bg-gray-800/60 group-focus:ring-4 group-focus:ring-white dark:group-focus:ring-gray-800/70 group-focus:outline-none">
      <svg class="w-4 h-4 text-white dark:text-gray-800 rtl:rotate-180" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 9 4-4-4-4"/>
      </svg>
      <span class="sr-only">Next</span>
    </span>
  </button>
</div>

app/views/home/_contact_us.html.erb
<hr class="mx-auto w-1/2 bg-black dark:bg-white" />

<section id="contact" class="widescreen:section-min-height tallscreen:section-min-height my-12 scroll-mt-16 p-6">
  <h2 class="mb-6 text-center text-4xl font-bold text-slate-900 sm:text-5xl dark:text-white">Contact Us</h2>
  <form action="./1.html" class="max-4-xl items-left mx-auto flex flex-col gap-4 text-2xl sm:text-3xl">
    <label for="subject">Subject:</label>
    <input type="text" name="subject" id="subject" required minlength="3" maxlength="60" placeholder="Your Subject" class="w-full rounded-xl border border-solid border-slate-900 p-3 text-2xl text-black sm:text-3xl dark:border-none" />
    <label for="message">Message:</label>
    <textarea name="message" id="message" cols="30" rows="10" placeholder="Your Message" required class="w-full rounded-xl border border-solid border-slate-900 p-3 text-2xl text-black sm:text-3xl dark:border-none"></textarea>
    <button class="dark:border:none w-48 rounded-xl border border-solid border-slate-900 bg-lime-500 p-3 text-white hover:bg-lime-600 active:bg-lime-400">Submit</button>
  </form>
</section>

app/views/home/_hero.html.erb
<section id="hero" class="widescreen:section-min-height tallscreen:section-min-height mb-12 flex scroll-mt-40 flex-col-reverse items-center justify-center gap-8 p-6 sm:flex-row">
  <article class="sm:w-1/2">
    <h2 class="max-w-md text-center text-4xl font-bold text-slate-900 sm:text-left sm:text-5xl dark:text-white">
      Home Fitness Solutions.<br />
      <span class="text-indigo-700 dark:text-indigo-300">Upgrade Your Body</span>
      Now!
    </h2>
    <p class="mt-4 max-w-md text-center text-2xl text-slate-700 sm:text-left dark:text-slate-400">Create a healthier version of yourself with our exercise equipment!</p>
    <p class="mt-4 max-w-md text-center text-2xl text-slate-700 sm:text-left dark:text-slate-400">
      <a href="#products" class="inline-block rounded bg-lime-500 px-4 py-2 font-bold text-white hover:bg-lime-600 active:bg-lime-400">SHOP NOW</a>
    </p>
  </article>
  <img class="w-1/2" src="/img/theme/hero.png" alt="Rocket Dab" />
</section>

app/views/home/_testimonials.html.erb
<hr class="mx-auto w-1/2 bg-black dark:bg-white" />

<section id="testimonials" class="widescreen:section-min-height tallscreen:section-min-height my-12 scroll-mt-20 p-6">
  <h2 class="mb-6 text-center text-4xl font-bold text-slate-900 sm:text-5xl dark:text-white">What our customers say:</h2>
  <figure class="my-12">
    <blockquote class="relative rounded-3xl bg-teal-600 py-12 pl-14 pr-8 dark:bg-black">
      <p
        class="before:trasform after:trasform mt-2 text-left text-2xl text-white before:absolute before:left-0 before:top-0 before:translate-x-2 before:translate-y-2 before:font-serif before:text-9xl before:text-white before:opacity-25 before:content-['\201C'] after:absolute after:-bottom-20 after:right-0 after:-translate-x-2 after:-translate-y-2 after:font-serif after:text-9xl after:text-white after:opacity-25 after:content-['\201D'] sm:text-3xl dark:text-slate-400">
        I stumbled upon this fitness store and found exactly what I needed &mdash; quality over quantity. This equipment have transformed my home workouts. Thanks for keeping it simple and effective!
      </p>
    </blockquote>
    <figcaption class="mt-2 text-right text-xl italic text-slate-500 sm:text-2xl dark:text-slate-400">&#8212;Sarah L</figcaption>
  </figure>
  <figure class="my-12">
    <blockquote class="relative rounded-3xl bg-teal-600 py-12 pl-14 pr-8 dark:bg-black">
      <p
        class="mt-2 text-left text-2xl text-white before:absolute before:left-0 before:top-0 before:translate-x-2 before:translate-y-2 before:transform before:font-serif before:text-9xl before:text-white before:opacity-25 before:content-['\201C'] after:absolute after:-bottom-20 after:right-0 after:-translate-x-2 after:-translate-y-2 after:transform after:font-serif after:text-9xl after:text-white after:opacity-25 after:content-['\201D'] sm:text-3xl dark:text-slate-400">
        The Automatic Rebound Ab Roller is a gem! I've been using it for a month, and my core is stronger than ever. This store's approach to fitness is spot on, and I'm a satisfied customer.
      </p>
    </blockquote>
    <figcaption class="mt-2 text-right text-xl italic text-slate-500 sm:text-2xl dark:text-slate-400">&#8212;David M</figcaption>
  </figure>
  <figure class="my-12">
    <blockquote class="relative rounded-3xl bg-teal-600 py-12 pl-14 pr-8 dark:bg-black">
      <p
        class="mt-2 text-left text-2xl text-white before:absolute before:left-0 before:top-0 before:translate-x-2 before:translate-y-2 before:transform before:font-serif before:text-9xl before:text-white before:opacity-25 before:content-['\201C'] after:absolute after:-bottom-20 after:right-0 after:-translate-x-2 after:-translate-y-2 after:transform after:font-serif after:text-9xl after:text-white after:opacity-25 after:content-['\201D'] sm:text-3xl dark:text-slate-400">
        This fitness store understands that less is more. The personalized service and handpicked equipment make all the difference. It's my go-to place for home fitness solutions.
      </p>
    </blockquote>
    <figcaption class="mt-2 text-right text-xl italic text-slate-500 sm:text-2xl dark:text-slate-400">&#8212;Jessica R</figcaption>
  </figure>
</section>

app/views/home/about.html.erb
<section id="about" class="widescreen:section-min-height tallscreen:section-min-height my-12 flex scroll-mt-16 flex-col items-start justify-center gap-8 p-6 sm:flex-row">
  <img class="sm:w-1/3 md:w-1/2 rounded-2xl" src="/img/theme/about.webp" alt="About HelsiFit" />
  <article class="sm:w-2/3 md:w-1/2">
    <h2 class="max-w-md text-center text-4xl font-bold text-slate-900 sm:text-left sm:text-5xl dark:text-white">
      <span class="text-indigo-700 dark:text-indigo-300">About HelsiFit</span>
    </h2>
    <p class="mt-4 max-w-md text-center text-2xl text-slate-700 sm:text-left dark:text-slate-400">At HelsiFit Fitness Store, we're dedicated to simplifying your path to a healthier, more active lifestyle. We believe in quality over quantity, offering meticulously selected exercise equipment to help you achieve your fitness goals efficiently at home.</p>
    <p class="mt-4 max-w-md text-center text-2xl text-slate-700 sm:text-left dark:text-slate-400">At our fitness store, we're more than just a business; we're a product of our own passion for fitness. We're not just store owners; we're constant fitness practitioners who have developed our own way of achieving efficient workouts at home. With our personal experiences and dedication, we understand the needs and challenges of those on their fitness journey. We are proud to share our knowledge and carefully curated equipment with you, so you too can experience the transformative power of our approach to home fitness.</p>
  </article>
</section>

app/views/home/index.html.erb
<%= render "hero" %>
<%= render "testimonials" %>
<% @featuring_products.each do |product| %>
  <%= render "products/featuring_product", product: %>
<% end %>
<%= render "products/products", products: @products %>
<%= render "about_us" %>
<%= render "contact_us" %>

app/views/layouts/_footer.html.erb
<footer id="footer" class="bg-indigo-800 text-xl text-white">
  <section class="mx-auto flex max-w-4xl flex-col p-4 sm:flex-row sm:justify-between">
    <address>
      <h2>HelsiFit</h2>
      Monday–Friday<br />
      9am–5pm EST<br />
      Email:
      <a href="mailto:info@helsifit.com">info@helsifit.com</a>
    </address>
    <nav class="hidden flex-col gap-2 md:flex" aria-label="footer">
      <a href="/#products" class="hover:opacity-90">Shop</a>
      <a href="/#testimonials" class="hover:opacity-90">Reviews</a>
      <a href="/#contact" class="hover:opacity-90">Contact Us</a>
    </nav>
    <nav class="hidden flex-col gap-2 md:flex" aria-label="footer">
      <a href="/policies/privacy-policy.html" class="hover:opacity-90">Privacy Policy</a>
      <a href="/policies/refund-policy.html" class="hover:opacity-90">Refund Policy</a>
      <a href="/policies/shipping-policy.html" class="hover:opacity-90">Shipping Policy</a>
      <a href="/policies/terms-of-service.html" class="hover:opacity-90">Terms of Service</a>
    </nav>
    <div class="flex flex-col sm:gap-2">
      <p class="text-right">Copyright &copy; <span id="year">2022</span></p>
      <p class="text-right">All Rights Reserved</p>
      <script>
        const year = document.getElementById('year');
        const thisYear = new Date().getFullYear();
        year.setAttribute('datetime', thisYear);
        year.textContent = thisYear;
      </script>
    </div>
  </section>
</footer>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en" class="sm:scroll-smooth">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>HelsiFit</title>
    <link rel="stylesheet" href="/css/style.css" />
    <script src="/js/main.js" defer></script>
    <script src="/js/flowbite.min.js" defer></script>
  </head>

  <body class="min-h-screen bg-slate-50 dark:bg-black dark:text-white">
    <%= render "layouts/header" %>
    <main class="mx-auto max-w-4xl">
      <%= yield %>
    </main>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/products/_featuring_product.html.erb
<hr class="mx-auto w-1/2 bg-black dark:bg-white" />

<section id="best-seller" class="bg-gray-100 dark:bg-black py-8 widescreen:section-min-height tallscreen:section-min-height my-12 scroll-mt-16 p-6">
  <div class="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
    <div class="flex flex-col md:flex-row -mx-4">
      <div class="md:flex-1 px-4">
        <div class="h-[460px] rounded-lg mb-2">
          <%= render "products/carousel", product: %>
        </div>
        <div class="flex -mx-2 mb-4">
          <div class="w-1/2 px-2">
            <button class="w-full bg-gray-900 dark:bg-gray-600 text-white py-2 px-4 rounded-full font-bold hover:bg-gray-800 dark:hover:bg-gray-700">Add to Cart</button>
          </div>
          <div class="w-1/2 px-2">
            <button class="w-full bg-gray-200 dark:bg-gray-700 text-gray-800 dark:text-white py-2 px-4 rounded-full font-bold hover:bg-gray-300 dark:hover:bg-gray-600">Add to Wishlist</button>
          </div>
        </div>
      </div>
      <div class="md:flex-1 px-4">
        <a href="<%= product_path(product) %>">
          <h1 class="text-4xl font-bold text-gray-800 dark:text-white mb-2">HelsiFit™ Ab Roller Wheel Automatic Rebound With Elbow Support</h1>
        </a>
        <div class="mb-2">
          <%= render "products/star_rating" %>
          <p class="mt-3"><span class="line-through text-lg">£95.99 GBP</span> <span class="font-bold text-xl px-2">£47.99 GBP</span> <span class="bg-red-700 text-white rounded-full px-3 py-0.5">Sale</span></p>
          <p class="text-sm mt-1 text-gray-500">Tax included. Free <a href="/policies/shipping-policy" class="underline">Shipping</a>.</p>
        </div>
        <div class="mb-4">
          <span class="font-bold text-gray-700 dark:text-gray-300">Select Color:</span>
          <div class="flex items-center mt-2">
            <button class="bg-gray-300 dark:bg-gray-700 text-gray-700 dark:text-white py-2 px-4 rounded-full font-bold mr-2 hover:bg-gray-400 dark:hover:bg-gray-600">Blue</button>
            <button class="bg-gray-300 dark:bg-gray-700 text-gray-700 dark:text-white py-2 px-4 rounded-full font-bold mr-2 hover:bg-gray-400 dark:hover:bg-gray-600">Orange</button>
          </div>
        </div>
        <div class="mb-4">
          <span class="font-bold text-gray-700 dark:text-gray-300">Select Size:</span>
          <div class="flex items-center mt-2">
            <button class="bg-gray-300 dark:bg-gray-700 text-gray-700 dark:text-white py-2 px-4 rounded-full font-bold mr-2 hover:bg-gray-400 dark:hover:bg-gray-600">S</button>
            <button class="bg-gray-300 dark:bg-gray-700 text-gray-700 dark:text-white py-2 px-4 rounded-full font-bold mr-2 hover:bg-gray-400 dark:hover:bg-gray-600">M</button>
            <button class="bg-gray-300 dark:bg-gray-700 text-gray-700 dark:text-white py-2 px-4 rounded-full font-bold mr-2 hover:bg-gray-400 dark:hover:bg-gray-600">L</button>
            <button class="bg-gray-300 dark:bg-gray-700 text-gray-700 dark:text-white py-2 px-4 rounded-full font-bold mr-2 hover:bg-gray-400 dark:hover:bg-gray-600">XL</button>
            <button class="bg-gray-300 dark:bg-gray-700 text-gray-700 dark:text-white py-2 px-4 rounded-full font-bold mr-2 hover:bg-gray-400 dark:hover:bg-gray-600">XXL</button>
          </div>
        </div>
        <div class="mb-4">
          <label for="quantity-input" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Quantity:</label>
          <div class="relative flex items-center max-w-[8rem]">
            <button type="button" id="decrement-button" data-input-counter-decrement="quantity-input" class="bg-gray-100 dark:bg-gray-700 dark:hover:bg-gray-600 dark:border-gray-600 hover:bg-gray-200 border border-gray-300 rounded-s-lg p-3 h-11 focus:ring-gray-100 dark:focus:ring-gray-700 focus:ring-2 focus:outline-none">
              <svg class="w-3 h-3 text-gray-900 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 18 2">
                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 1h16"/>
              </svg>
            </button>
            <input type="text" id="quantity-input" data-input-counter aria-describedby="helper-text-explanation" class="bg-gray-50 border-x-0 border-gray-300 h-10 text-center text-gray-900 text-sm focus:ring-blue-500 focus:border-blue-500 block w-10 py-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="1" value="1" required />
            <button type="button" id="increment-button" data-input-counter-increment="quantity-input" class="bg-gray-100 dark:bg-gray-700 dark:hover:bg-gray-600 dark:border-gray-600 hover:bg-gray-200 border border-gray-300 rounded-e-lg p-3 h-11 focus:ring-gray-100 dark:focus:ring-gray-700 focus:ring-2 focus:outline-none">
              <svg class="w-3 h-3 text-gray-900 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 18 18">
                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 1v16M1 9h16"/>
              </svg>
            </button>
          </div>
          <p id="helper-text-explanation" class="mt-2 text-sm text-gray-500 dark:text-gray-400">Limited stock! 🔥 6 people are viewing this and 4 recently purchased it.</p>
        </div>
        <div class="w-full -mx-2 mb-8 px-2 pt-4">
          <button class="w-full bg-gray-900 dark:bg-gray-600 text-white py-2 px-4 rounded-full font-bold hover:bg-gray-800 dark:hover:bg-gray-700">Add to Cart</button>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/products/_product.html.erb
<div class="bg-white rounded-2xl cursor-pointer hover:-translate-y-2 transition-all relative">
  <a href="<%= product_path(product) %>">
    <%= render "products/sale_badge" if product.sale %>
    <div class="w-11/12 h-[210px] overflow-hidden mx-auto aspect-w-16 aspect-h-8 mb-1">
      <img src="<%= product.first_image_src %>" alt="<%= product.title %>"
        class="h-full w-full object-contain" />
    </div>
    <div class="px-2 pb-2 mx-auto">
      <h3 class="font-bold text-gray-800"><%= product.title %></h3>
      <h4 class="text-gray-800 mt-4 mb-4">
        <% if product.sale %>
          <span class="text-gray-300 line-through">£<%= product.outdated_price %>&nbsp;GBP</span>
        <% end %>
        £<%= product.price["GBP"].to_f / 100 %>&nbsp;GBP
      </h4>
    </div>
  </a>
</div>